apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-db
  namespace: e-commerce
spec:
  selector:
    matchLabels:
      app: delivery-db
  template:
    metadata:
      labels:
        app: delivery-db
    spec:
      containers:
        - name: delivery-db
          image: postgres:15
          ports:
              - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "1783"
            - name: POSTGRES_DB
              value: "delivery"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: delivery-pvc
