apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: e-commerce
spec:
  replicas: 2
  selector:
   matchLabels:
     app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: delivery_service-delivery_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://delivery-db-service:5432/delivery
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1783"
